config/routes.rb
Rails.application.routes.draw do

  post '/cities/get_city' => 'cities#get_city'

  get '/users/get_cities' => 'users#get_cities'
  
  resources :cities

  root 'users#show'

  delete '/articles' => 'articles#destroy'
  delete '/photos' => 'photos#destroy'
  delete '/tweets' => 'tweets#destroy'

  get '/users/signed_in' 

  get '/autocomplete/countries' => 'autocomplete#show'

  get '/photos/flickr'
  get '/twitter' =>'tweets#twitter_update'
  get '/auth/twitter', as: 'twitter_login'
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, :only => [:show]
  resources :articles, :only => [:create, :index]
  resources :photos, :only => [:create, :index]
  resources :tweets, :only => [:create, :index]

end

app/views/layouts/_about.html.erb
<div class="col-md-9 about" id="creators">
  <center><h4>Created By</h4></center>
  <div class="contributors">
    <div class="contributor">
      <div id="ed">
      </div>
     <center> <p>Edward Warren</p></center>
     <center><%= link_to image_tag('/assets/github.png', height: '25px', width: '25px'), 'https://github.com/ewarren7/', target: '_blank' %>
      <%= link_to image_tag('linkedin.png', height: '25px', width: '25px'), 'https://www.linkedin.com/in/edwardiwarren/', target: '_blank' %>
      <%= link_to image_tag('twitter3.png', height: '25px', width: '25px'), 'https://www.twitter.com/ewarren7', target: '_blank' %>
    </center>
    </div>
    <div class="contributor">
      <div id="amber">
      </div>
      <center><p>Amber Tunnell</p></center>
       <center><%= link_to image_tag('/assets/github.png', height: '25px', width: '25px'), 'https://github.com/ambertunnell/', target: '_blank' %>
        <%= link_to image_tag('linkedin.png', height: '25px', width: '25px'), 'https://www.linkedin.com/in/ambertunnell/', target: '_blank' %>
        <%= link_to image_tag('twitter3.png', height: '25px', width: '25px'), 'http://www.twitter.com/ambertunnell', target: '_blank' %>
      </center>
      </div>
    <div class="contributor">
      <div id="koren">
      </div>
      <center><p>Koren Leslie Cohen</p></center>
      <center><%= link_to image_tag('/assets/github.png', height: '25px', width: '25px'), 'https://github.com/KorenLeslieCohen/', target: '_blank' %>
        <%= link_to image_tag('linkedin.png', height: '25px', width: '25px'), 'https://www.linkedin.com/in/korenlesliecohen/', target: '_blank' %>
        <%= link_to image_tag('twitter3.png', height: '25px', width: '25px'), 'https://www.twitter.com/korenlc', target: '_blank' %>
      </center>
    </div>
    <div class="contributor">
      <div id="ben">
      </div>
      <center> <p>Ben Serviss</p></center>
      <center><%= link_to image_tag('/assets/github.png', height: '25px', width: '25px'), 'https://github.com/kamoh/', target: '_blank' %>
        <%= link_to image_tag('linkedin.png', height: '25px', width: '25px'), 'https://www.linkedin.com/in/benserviss', target: '_blank' %>
        <%= link_to image_tag('twitter3.png', height: '25px', width: '25px'), 'https://www.twitter.com/benserviss', target: '_blank' %>
      </center>
    </div>
  </div>
  <center><h5><a href="#top">worldview</a> provides users with curated media from thousands of searchable locations around the world using the Twitter, Forecast.io, Weather Underground, Flickr and New York Times APIs. Users can log in through Twitter OAuth, where they will have the ability to save all content to a personalized dashboard. <%= render 'layouts/more' %></a></h5></center>
</div>

app/views/layouts/_city_select.html.erb
<form action=''>
  <select name='cities'>
    <option value='new+york'>New York</option>
    <option value='london'>London</option>
    <option value='hong+kong'>Hong Kong</option>
    <option value='paris'>Paris</option>
    <option value="sydney">Sydney</option>
  </select>
</form>

app/views/layouts/_clocks.html.erb
<center>
<div class="head-container" id="top">
<!-- <div id="top"> -->

<div class="clock-title">
  <h1>worldview</h1>
  <h6>Click a clock.</h6>
</div>
  
<div class="row clock-row">
  <div id="clock-container">

    <div class="initial1-clock col-md-2 clock" data-city="initial">
   
    </div>
    <div class="initial2-clock col-md-2 clock" data-city="initial">
      
    </div>
    <div class="initial3-clock col-md-2 clock" data-city="initial">
     
    </div> 
    <div class="initial4-clock col-md-2 clock" data-city="initial">
     
    </div> 
    <div class="initial5-clock col-md-2 clock" data-city="initial">
     
    </div>  

    <% unless logged_in? %> 
      <div class="login">
        <center>
          <div id="invalid_city" style="color:white">&nbsp;</div>
          <form onsubmit="return submit_new_city();">
            <input type="text" id="new-city" placeholder="Add a city...">
          </form>
          <!-- <a href="#"><img src="/assets/shim.png" id="login-shim"></a> -->
          <%= link_to image_tag('shim.png', id: 'login-shim'), twitter_login_path %>
          <p>
            <%= link_to image_tag('twitter.png', height: '20px', width: '20px'), twitter_login_path %><br>
            <%= link_to 'Login with Twitter', twitter_login_path %>
          </p><br><br>
            

        </center>
      </div>
    <% else %>
      <div class="login" id="invalid_city" style="color:white">&nbsp;</div>
      <form onsubmit="return submit_new_city();">
        <input type="text" id="new-city" placeholder="Add a city...">
      </form>
    <% end %> 
  </div>
</center>

app/views/layouts/_dashboard.html.erb
<a id="dashboard-link" href="#dashboard"><%= "DASHBOARD" %>
<%#= "WELCOME, #{current_user.first_name.upcase}!" %>
</a>

<div id="dashboard">
  <div class="modal-box">
    <a id="dashboard-xlink" href="#" title="Close" class="close">X</a>
    <div class="modal-text">

      <center><h4>DASHBOARD</h4></center>

    <div class="dashboard-photo">
      <center><h4><%= current_user.name %></h4></center>
      <center><%= image_tag current_user.image %></center>
    </div>
    
    <div style="height: 20px"></div>

    <div class="col-dashboard-news">
      <center><h4>Favorited Articles</h4></center>
      <ul class='dashboard-articles'>
      </ul>
    </div>  

    <div class="col-dashboard-photos">
      <center><h4>Favorited Photos</h4></center>
      <ul class="dashboard-photos">
      </ul>
    </div>  
    
    <div class="col-dashboard-tweets">  
      <center><h4>Favorited Tweets</h4></center>
      <ul class="dashboard-tweets1">
      </ul>
      <ul class="dashboard-tweets2">
      </ul>
      <ul class="dashboard-tweets3">
      </ul>
    </div>  
 
    </div>
  </div>
</div>      

app/views/layouts/_footer.html.erb
<footer>
  <center><p>&copy; <a href="#top">worldview</a> 2014 | Built with &hearts; by <a href="http://www.twitter.com/ewarren7" target="_blank">Edward Warren</a>, <a href="http://www.twitter.com/ambertunnell" target="_blank">Amber Tunnell</a>, <a href="http://www.twitter.com/korenlc" target="_blank">Koren Leslie Cohen</a> &amp; <a href="http://www.twitter.com/benserviss" target="_blank">Ben Serviss</a></p></center>
</footer>  

app/views/layouts/_more.html.erb
<br><br>Want to know how worldview works? <a href = "#" onclick = "document.getElementById('light').style.display='block';document.getElementById('fade').style.display='block'">Read more</a>.

<div id="light" class="white_content"><h4>What's in a worldview?</h4><br>
    <a id="dashboard-xlink" href="#" title="Close" class="close" onclick = "document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none'">X</a>
    <!-- <a href = "#" >Close</a> -->
<div class="modal-box">
    <div class="modal-text">
  <div>
  <div id="about-col-1"><br><br>
    <img src="/assets/worldview_flow.png" width="710px" height="911px">
  </div>
  <div id="about-col-2"><br><br>
    How do we find up-to-the-minute information on almost every city in the world in just a click? Behind the scenes, worldview works with five APIs to pull detailed data about each city.

    <h2>Creating the Clock</h2>

    When you enter in a new city, the name is sent to <%= link_to 'Weather Underground', 'http://www.wunderground.com/weather/api/', target: '_blank' %>'s Autocomplete API, which matches your input with the most relevant city and returns its name, state, country and coordinates.<br><br>

    Next, this information is sent to <%= link_to 'Forecast.io', 'https://developer.forecast.io/', target: '_blank' %>, which returns the UTC Offset to generate that city's current time. With this information, worldview creates a new clock representing that city.

    <h2>Finding the Data</h2>

    With the city's clock created and saved to the database, the next step relies on you.<br><br>

    When you click the clock, all the information previously gathered is split up into separate API calls and sent out to <%= link_to 'The New York Times', 'http://developer.nytimes.com/docs', target: '_blank' %> for news, <%= link_to 'Forecast.io', 'https://developer.forecast.io/', target: '_blank' %> once again for the current weather, <%= link_to 'Flickr', 'https://www.flickr.com/services/api/', target: '_blank' %> for tagged photos and <%= link_to 'Twitter', 'https://dev.twitter.com/', target: '_blank' %> for trending tweets carrying the city's hashtag.

    <h2>Instant Updates</h2>

    <%= link_to 'worldview','http://world-view.today' %> makes liberal use of AJAX (Asyncronous JavaScript and XML) calls to request and fetch data instantly. This allows the site to function on a single page for a truly seamless experience.<br><br>

    <div class="clearfix"></div>
  </div>
</div>
          
<br>
</div>
    
    </div>
</div>
<div id="fade" class="black_overlay"></div>

app/views/layouts/_navbar.html.erb
<!-- <div class="container"> -->
<nav>
<div class="navbar navbar-default">
  <div class="navbar-inner">
    <div class="navbar-header">
      <a class="navbar-brand" href="#top">WORLDVIEW</a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div>
      <div class="collapse navbar-collapse navbar-responsive-collapse"> 
      <ul class="nav navbar-nav navbar-left">
         <li><a id="current-location">CURRENT LOCATION: </a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right" id="nav-highlight">
        <% if logged_in? %>
          <li><a href="#weather-anchor" id="#weather-anch">WEATHER</a></li>
          <li><a href="#news-anchor">NEWS</a></li>
          <li><a href="#photos-anchor">PHOTOS</a></li>
          <li><a href="#tweets-anchor">TWEETS</a></li>
          <li><a href="#creators">ABOUT</a></li>
 <!--           <li><a>
            <select name='cities'>
              <option value='default'>Choose a City</option>
              <%# @cities.each do |city| %>
                <%# if !current_user.cities.include?(city) %>
                  <option value='<%#= city.name %>'><%#= city.name %></option>
                <%# end %>
              <%# end %>
            </select>
          </li> -->
          <li><%= render 'layouts/dashboard' %></li>
          <li><%= link_to 'LOG OUT', logout_path %></li>
        <% else %>
          <li><a href="#weather-anchor" id="#weather-anch">WEATHER</a></li>
          <li><a href="#news-anchor">NEWS</a></li>
          <li><a href="#photos-anchor">PHOTOS</a></li>
          <li><a href="#tweets-anchor">TWEETS</a></li>
          <li><a href="#creators">ABOUT</a></li>
          <li><%= link_to 'LOG IN WITH TWITTER', twitter_login_path %></li>
        <% end %> 
      </ul>
    </div>
    </div>
  </div>
</div>
</nav>
<!-- </div> -->

app/views/layouts/_profile.html.erb
<a id="dashboard-link" href="#dashboard">My Profile</a>

<div id="dashboard">
  <div class="modal-box">
    <a id="dashboard-xlink" href="#" title="Close" class="close">X</a>
    <div class="modal-text">

      <h3>Personal Dashboard</h3>

      <h4>Favorited Articles</h4>
      <ul class="dashboard-articles">
      </ul>

      <h4>Favorited Photos</h4>
      <ul class="dashboard-photos">
      </ul>

      <h4>Favorited Tweets</h4>
      <ul class="dashboard-tweets">
      </ul>

    </div>
  </div>
</div>      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>worldview</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta property="og:image" content="screenshot-newmain.png" />
  <%= analytics_init if Rails.env.production? %>
  <meta name="keywords" content="Koren Leslie Cohen, Amber Tunnell, Edward Warren, Ben Serviss, The Flatiron School, world clocks, javascript, ajax, rails, curated media"/>
  <meta name="description" content="Web application utilizing Forecast.io, Twitter, Weather Underground, New York Times, and Flickr APIs to provide curated content from thousands of searchable cities around the world.">
</head>
<body id="scroll">
  <%= render "layouts/navbar" %> 
  <center>
    <%= yield %>
  </center> 
  <!-- Google Analytics Info -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-53783034-1', 'auto');
      ga('send', 'pageview');
    </script>
    <!-- end analytics -->
</body>
</html>